using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Info.Academico
{
    public class aca_Admision_Info
    {
        public int IdEmpresa { get; set; }
        public decimal IdAdmision { get; set; }
        public int IdSede { get; set; }
        public int IdAnio { get; set; }
        public int IdJornada { get; set; }
        public int IdNivel { get; set; }
        public int IdCurso { get; set; }
        public string Naturaleza_Aspirante { get; set; }
        public string IdTipoDocumento_Aspirante { get; set; }
        public string CedulaRuc_Aspirante { get; set; }
        public string Nombres_Aspirante { get; set; }
        public string Apellidos_Aspirante { get; set; }
        public string NombreCompleto_Aspirante { get; set; }
        public string Direccion_Aspirante { get; set; }
        public string Telefono_Aspirante { get; set; }
        public string Celular_Aspirante { get; set; }
        public string Correo_Aspirante { get; set; }
        public string Sexo_Aspirante { get; set; }
        public Nullable<System.DateTime> FechaNacimiento_Aspirante { get; set; }
        public string CodCatalogoSangre_Aspirante { get; set; }
        public string CodCatalogoCONADIS_Aspirante { get; set; }
        public Nullable<double> PorcentajeDiscapacidad_Aspirante { get; set; }
        public string NumeroCarnetConadis_Aspirante { get; set; }
        public Nullable<int> IdGrupoEtnico_Aspirante { get; set; }
        public Nullable<int> IdReligion_Aspirante { get; set; }
        public Nullable<bool> AsisteCentroCristiano_Aspirante { get; set; }
        public string LugarNacimiento_Aspirante { get; set; }
        public string IdPais_Aspirante { get; set; }
        public string Cod_Region_Aspirante { get; set; }
        public string IdProvincia_Aspirante { get; set; }
        public string IdCiudad_Aspirante { get; set; }
        public string IdParroquia_Aspirante { get; set; }
        public string Sector_Aspirante { get; set; }
        public System.DateTime FechaIngreso_Aspirante { get; set; }
        public int IdCatalogoFichaTipoViv_Aspirante { get; set; }
        public int IdCatalogoFichaViv_Aspirante { get; set; }
        public int IdCatalogoFichaAgua_Aspirante { get; set; }
        public bool TieneElectricidad_Aspirante { get; set; }
        public bool TieneHermanos_Aspirante { get; set; }
        public int IdCatalogoFichaMotivo_Aspirante { get; set; }
        public int IdCatalogoFichaInst_Aspirante { get; set; }
        public int IdCatalogoFichaFinanc_Aspirante { get; set; }
        public int IdCatalogoFichaVive_Aspirante { get; set; }
        public string OtroMotivoIngreso_Aspirante { get; set; }
        public string OtroInformacionInst_Aspirante { get; set; }
        public string OtroFinanciamiento_Aspirante { get; set; }
        public string Naturaleza_Padre { get; set; }
        public string IdTipoDocumento_Padre { get; set; }
        public string CedulaRuc_Padre { get; set; }
        public string Nombres_Padre { get; set; }
        public string Apellidos_Padre { get; set; }
        public string NombreCompleto_Padre { get; set; }
        public string RazonSocial_Padre { get; set; }
        public string Direccion_Padre { get; set; }
        public string Telefono_Padre { get; set; }
        public string Celular_Padre { get; set; }
        public string Correo_Padre { get; set; }
        public string Sexo_Padre { get; set; }
        public Nullable<System.DateTime> FechaNacimiento_Padre { get; set; }
        public string CodCatalogoSangre_Padre { get; set; }
        public string CodCatalogoCONADIS_Padre { get; set; }
        public Nullable<double> PorcentajeDiscapacidad_Padre { get; set; }
        public string NumeroCarnetConadis_Padre { get; set; }
        public Nullable<int> IdGrupoEtnico_Padre { get; set; }
        public Nullable<int> IdReligion_Padre { get; set; }
        public string IdEstadoCivil_Padre { get; set; }
        public bool AsisteCentroCristiano_Padre { get; set; }
        public string IdPais_Padre { get; set; }
        public string Cod_Region_Padre { get; set; }
        public string IdProvincia_Padre { get; set; }
        public string IdCiudad_Padre { get; set; }
        public string IdParroquia_Padre { get; set; }
        public string Sector_Padre { get; set; }
        public int IdCatalogoPAREN_Padre { get; set; }
        public Nullable<int> IdCatalogoFichaInst_Padre { get; set; }
        public string EmpresaTrabajo_Padre { get; set; }
        public string DireccionTrabajo_Padre { get; set; }
        public string TelefonoTrabajo_Padre { get; set; }
        public string CargoTrabajo_Padre { get; set; }
        public Nullable<int> AniosServicio_Padre { get; set; }
        public Nullable<double> IngresoMensual_Padre { get; set; }
        public bool VehiculoPropio_Padre { get; set; }
        public string Marca_Padre { get; set; }
        public string Modelo_Padre { get; set; }
        public Nullable<int> AnioVehiculo_Padre { get; set; }
        public bool CasaPropia_Padre { get; set; }
        public bool EstaFallecido_Padre { get; set; }
        public string Naturaleza_Madre { get; set; }
        public string IdTipoDocumento_Madre { get; set; }
        public string CedulaRuc_Madre { get; set; }
        public string Nombres_Madre { get; set; }
        public string Apellidos_Madre { get; set; }
        public string NombreCompleto_Madre { get; set; }
        public string RazonSocial_Madre { get; set; }
        public string Direccion_Madre { get; set; }
        public string Telefono_Madre { get; set; }
        public string Celular_Madre { get; set; }
        public string Correo_Madre { get; set; }
        public string Sexo_Madre { get; set; }
        public Nullable<System.DateTime> FechaNacimiento_Madre { get; set; }
        public string CodCatalogoSangre_Madre { get; set; }
        public string CodCatalogoCONADIS_Madre { get; set; }
        public Nullable<double> PorcentajeDiscapacidad_Madre { get; set; }
        public string NumeroCarnetConadis_Madre { get; set; }
        public Nullable<int> IdGrupoEtnico_Madre { get; set; }
        public Nullable<int> IdReligion_Madre { get; set; }
        public string IdEstadoCivil_Madre { get; set; }
        public bool AsisteCentroCristiano_Madre { get; set; }
        public string IdPais_Madre { get; set; }
        public string Cod_Region_Madre { get; set; }
        public string IdProvincia_Madre { get; set; }
        public string IdCiudad_Madre { get; set; }
        public string IdParroquia_Madre { get; set; }
        public string Sector_Madre { get; set; }
        public int IdCatalogoPAREN_Madre { get; set; }
        public Nullable<int> IdCatalogoFichaInst_Madre { get; set; }
        public string EmpresaTrabajo_Madre { get; set; }
        public string DireccionTrabajo_Madre { get; set; }
        public string TelefonoTrabajo_Madre { get; set; }
        public string CargoTrabajo_Madre { get; set; }
        public Nullable<int> AniosServicio_Madre { get; set; }
        public Nullable<double> IngresoMensual_Madre { get; set; }
        public bool VehiculoPropio_Madre { get; set; }
        public string Marca_Madre { get; set; }
        public string Modelo_Madre { get; set; }
        public Nullable<int> AnioVehiculo_Madre { get; set; }
        public bool CasaPropia_Madre { get; set; }
        public bool EstaFallecido_Madre { get; set; }
        public string Naturaleza_Representante { get; set; }
        public string IdTipoDocumento_Representante { get; set; }
        public string CedulaRuc_Representante { get; set; }
        public string Nombres_Representante { get; set; }
        public string Apellidos_Representante { get; set; }
        public string NombreCompleto_Representante { get; set; }
        public string RazonSocial_Representante { get; set; }
        public string Direccion_Representante { get; set; }
        public string Telefono_Representante { get; set; }
        public string Celular_Representante { get; set; }
        public string Correo_Representante { get; set; }
        public string Sexo_Representante { get; set; }
        public Nullable<System.DateTime> FechaNacimiento_Representante { get; set; }
        public string CodCatalogoSangre_Representante { get; set; }
        public string CodCatalogoCONADIS_Representante { get; set; }
        public Nullable<double> PorcentajeDiscapacidad_Representante { get; set; }
        public string NumeroCarnetConadis_Representante { get; set; }
        public Nullable<int> IdGrupoEtnico_Representante { get; set; }
        public Nullable<int> IdReligion_Representante { get; set; }
        public string IdEstadoCivil_Representante { get; set; }
        public bool AsisteCentroCristiano_Representante { get; set; }
        public string IdPais_Representante { get; set; }
        public string Cod_Region_Representante { get; set; }
        public string IdProvincia_Representante { get; set; }
        public string IdCiudad_Representante { get; set; }
        public string IdParroquia_Representante { get; set; }
        public string Sector_Representante { get; set; }
        public int IdCatalogoPAREN_Representante { get; set; }
        public Nullable<int> IdCatalogoFichaInst_Representante { get; set; }
        public string EmpresaTrabajo_Representante { get; set; }
        public string DireccionTrabajo_Representante { get; set; }
        public string TelefonoTrabajo_Representante { get; set; }
        public string CargoTrabajo_Representante { get; set; }
        public Nullable<int> AniosServicio_Representante { get; set; }
        public Nullable<double> IngresoMensual_Representante { get; set; }
        public bool VehiculoPropio_Representante { get; set; }
        public string Marca_Representante { get; set; }
        public string Modelo_Representante { get; set; }
        public Nullable<int> AnioVehiculo_Representante { get; set; }
        public bool CasaPropia_Representante { get; set; }
        public bool EstaFallecido_Representante { get; set; }
        public double SueldoPadre { get; set; }
        public double SueldoMadre { get; set; }
        public double OtroIngresoPadre { get; set; }
        public double OtroIngresoMadre { get; set; }
        public double GastoAlimentacion { get; set; }
        public double GastoEducacion { get; set; }
        public double GastoServicioBasico { get; set; }
        public double GastoSalud { get; set; }
        public double GastoArriendo { get; set; }
        public double GastoPrestamo { get; set; }
        public double OtroGasto { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    }
}
