//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_MatriculaConducta
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public Nullable<decimal> PromedioP1 { get; set; }
        public Nullable<decimal> PromedioFinalP1 { get; set; }
        public Nullable<decimal> PromedioP2 { get; set; }
        public Nullable<decimal> PromedioFinalP2 { get; set; }
        public Nullable<decimal> PromedioP3 { get; set; }
        public Nullable<decimal> PromedioFinalP3 { get; set; }
        public Nullable<decimal> PromedioQ1 { get; set; }
        public Nullable<decimal> PromedioFinalQ1 { get; set; }
        public Nullable<decimal> PromedioP4 { get; set; }
        public Nullable<decimal> PromedioFinalP4 { get; set; }
        public Nullable<decimal> PromedioP5 { get; set; }
        public Nullable<decimal> PromedioFinalP5 { get; set; }
        public Nullable<decimal> PromedioP6 { get; set; }
        public Nullable<decimal> PromedioFinalP6 { get; set; }
        public Nullable<decimal> PromedioQ2 { get; set; }
        public Nullable<decimal> PromedioFinalQ2 { get; set; }
        public Nullable<decimal> PromedioGeneral { get; set; }
        public Nullable<decimal> PromedioFinal { get; set; }
    
        public virtual aca_Matricula aca_Matricula { get; set; }
    }
}
