//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_Reporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aca_Reporte()
        {
            this.aca_Reporte_x_seg_usuario = new HashSet<aca_Reporte_x_seg_usuario>();
            this.aca_Reporte_x_tb_empresa = new HashSet<aca_Reporte_x_tb_empresa>();
        }
    
        public string CodReporte { get; set; }
        public string nom_reporte { get; set; }
        public string CodModulo { get; set; }
        public string rpt_vista { get; set; }
        public bool rpt_usa_store_procedure { get; set; }
        public string rpt_store_procedure { get; set; }
        public string rpt_clase_info { get; set; }
        public string rpt_clase_data { get; set; }
        public string rpt_clase_bus { get; set; }
        public string rpt_clase_rpt { get; set; }
        public string mvc_area { get; set; }
        public string mvc_controlador { get; set; }
        public string mvc_accion { get; set; }
        public bool estado { get; set; }
        public bool se_muestra_administrador_reportes { get; set; }
        public int orden { get; set; }
        public string observacion { get; set; }
        public bool Se_Mustra_Disenador_rpt { get; set; }
        public virtual tb_modulo tb_modulo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aca_Reporte_x_seg_usuario> aca_Reporte_x_seg_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aca_Reporte_x_tb_empresa> aca_Reporte_x_tb_empresa { get; set; }
    }
}
