//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_AlumnoDocumento
    {
        public int IdEmpresa { get; set; }
        public decimal IdAlumno { get; set; }
        public int Secuencia { get; set; }
        public int IdDocumento { get; set; }
        public bool EnArchivo { get; set; }
    
        public virtual aca_Documento aca_Documento { get; set; }
        public virtual aca_Alumno aca_Alumno { get; set; }
    }
}
