//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_MatriculaConducta
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public Nullable<int> PromedioP1 { get; set; }
        public Nullable<int> PromedioFinalP1 { get; set; }
        public Nullable<int> PromedioP2 { get; set; }
        public Nullable<int> PromedioFinalP2 { get; set; }
        public Nullable<int> PromedioP3 { get; set; }
        public Nullable<int> PromedioFinalP3 { get; set; }
        public Nullable<int> PromedioQ1 { get; set; }
        public Nullable<int> PromedioFinalQ1 { get; set; }
        public Nullable<int> PromedioP4 { get; set; }
        public Nullable<int> PromedioFinalP4 { get; set; }
        public Nullable<int> PromedioP5 { get; set; }
        public Nullable<int> PromedioFinalP5 { get; set; }
        public Nullable<int> PromedioP6 { get; set; }
        public Nullable<int> PromedioFinalP6 { get; set; }
        public Nullable<int> PromedioQ2 { get; set; }
        public Nullable<int> PromedioFinalQ2 { get; set; }
        public Nullable<int> PromedioGeneral { get; set; }
        public Nullable<int> PromedioFinal { get; set; }
    
        public virtual aca_Matricula aca_Matricula { get; set; }
    }
}
