//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_MatriculaCalificacionCualitativaPromedio
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public int IdMateria { get; set; }
        public Nullable<decimal> IdProfesor { get; set; }
        public Nullable<int> IdCalificacionCualitativaQ1 { get; set; }
        public Nullable<decimal> PromedioQ1 { get; set; }
        public Nullable<int> IdCalificacionCualitativaQ2 { get; set; }
        public Nullable<decimal> PromedioQ2 { get; set; }
        public Nullable<int> IdCalificacionCualitativaFinal { get; set; }
        public Nullable<decimal> PromedioFinal { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
