//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_AnioLectivoCalificacionHistorico
    {
        public int IdEmpresa { get; set; }
        public int IdAnio { get; set; }
        public decimal IdAlumno { get; set; }
        public Nullable<decimal> IdMatricula { get; set; }
        public int IdNivel { get; set; }
        public int IdCurso { get; set; }
        public string AntiguaInstitucion { get; set; }
        public decimal Promedio { get; set; }
        public Nullable<int> IdEquivalenciaPromedio { get; set; }
        public decimal Conducta { get; set; }
        public Nullable<int> SecuenciaConducta { get; set; }
    
        public virtual aca_Alumno aca_Alumno { get; set; }
        public virtual aca_AnioLectivoConductaEquivalencia aca_AnioLectivoConductaEquivalencia { get; set; }
        public virtual aca_AnioLectivoEquivalenciaPromedio aca_AnioLectivoEquivalenciaPromedio { get; set; }
        public virtual aca_Curso aca_Curso { get; set; }
        public virtual aca_NivelAcademico aca_NivelAcademico { get; set; }
        public virtual aca_AnioLectivo aca_AnioLectivo { get; set; }
    }
}
