//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_MatriculaCondicional_Det
    {
        public int IdEmpresa { get; set; }
        public decimal IdCondicional { get; set; }
        public int Secuencia { get; set; }
        public int IdParrafo { get; set; }
    
        public virtual aca_MatriculaCondicional aca_MatriculaCondicional { get; set; }
        public virtual aca_MatriculaCondicionalParrafo aca_MatriculaCondicionalParrafo { get; set; }
    }
}
