//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_AnioLectivoEquivalenciaPromedio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aca_AnioLectivoEquivalenciaPromedio()
        {
            this.aca_MatriculaCalificacion = new HashSet<aca_MatriculaCalificacion>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdEquivalenciaPromedio { get; set; }
        public int IdAnio { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public decimal ValorMinimo { get; set; }
        public decimal ValorMaximo { get; set; }
    
        public virtual aca_AnioLectivo aca_AnioLectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aca_MatriculaCalificacion> aca_MatriculaCalificacion { get; set; }
    }
}
