//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_MatriculaConducta
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public Nullable<int> SecuenciaPromedioP1 { get; set; }
        public Nullable<double> PromedioP1 { get; set; }
        public Nullable<int> SecuenciaPromedioFinalP1 { get; set; }
        public Nullable<double> PromedioFinalP1 { get; set; }
        public Nullable<int> SecuenciaPromedioP2 { get; set; }
        public Nullable<double> PromedioP2 { get; set; }
        public Nullable<int> SecuenciaPromedioFinalP2 { get; set; }
        public Nullable<double> PromedioFinalP2 { get; set; }
        public Nullable<int> SecuenciaPromedioP3 { get; set; }
        public Nullable<double> PromedioP3 { get; set; }
        public Nullable<int> SecuenciaPromedioFinalP3 { get; set; }
        public Nullable<double> PromedioFinalP3 { get; set; }
        public Nullable<int> SecuenciaPromedioQ1 { get; set; }
        public Nullable<double> PromedioQ1 { get; set; }
        public Nullable<int> SecuenciaPromedioFinalQ1 { get; set; }
        public Nullable<double> PromedioFinalQ1 { get; set; }
        public Nullable<int> SecuenciaPromedioP4 { get; set; }
        public Nullable<double> PromedioP4 { get; set; }
        public Nullable<int> SecuenciaPromedioFinalP4 { get; set; }
        public Nullable<double> PromedioFinalP4 { get; set; }
        public Nullable<int> SecuenciaPromedioP5 { get; set; }
        public Nullable<double> PromedioP5 { get; set; }
        public Nullable<int> SecuenciaPromedioFinalP5 { get; set; }
        public Nullable<double> PromedioFinalP5 { get; set; }
        public Nullable<int> SecuenciaPromedioP6 { get; set; }
        public Nullable<double> PromedioP6 { get; set; }
        public Nullable<int> SecuenciaPromedioFinalP6 { get; set; }
        public Nullable<double> PromedioFinalP6 { get; set; }
        public Nullable<int> SecuenciaPromedioQ2 { get; set; }
        public Nullable<double> PromedioQ2 { get; set; }
        public Nullable<int> SecuenciaPromedioFinalQ2 { get; set; }
        public Nullable<double> PromedioFinalQ2 { get; set; }
        public Nullable<int> SecuenciaPromedioGeneral { get; set; }
        public Nullable<double> PromedioGeneral { get; set; }
        public Nullable<int> SecuenciaPromedioFinal { get; set; }
        public Nullable<double> PromedioFinal { get; set; }
    
        public virtual aca_Matricula aca_Matricula { get; set; }
    }
}
