//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_AnioLectivo_Rubro_Periodo
    {
        public int IdEmpresa { get; set; }
        public int IdAnio { get; set; }
        public int IdRubro { get; set; }
        public int IdPeriodo { get; set; }
        public int Secuencia { get; set; }
        public string Observacion { get; set; }
    
        public virtual aca_AnioLectivo_Periodo aca_AnioLectivo_Periodo { get; set; }
        public virtual aca_AnioLectivo_Rubro aca_AnioLectivo_Rubro { get; set; }
    }
}
