//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_Matricula_Rubro
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public int IdPeriodo { get; set; }
        public int IdRubro { get; set; }
        public int IdAnio { get; set; }
        public int IdPlantilla { get; set; }
        public decimal IdMecanismo { get; set; }
        public decimal IdProducto { get; set; }
        public bool EnMatricula { get; set; }
        public decimal Subtotal { get; set; }
        public string IdCod_Impuesto_Iva { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal ValorIVA { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<decimal> IdCbteVta { get; set; }
        public Nullable<System.DateTime> FechaFacturacion { get; set; }
    
        public virtual aca_MecanismoDePago aca_MecanismoDePago { get; set; }
        public virtual aca_Plantilla aca_Plantilla { get; set; }
        public virtual aca_Rubro aca_Rubro { get; set; }
        public virtual aca_Matricula aca_Matricula { get; set; }
    }
}
