//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_AnioLectivo_Curso_Documento
    {
        public int IdEmpresa { get; set; }
        public int IdAnio { get; set; }
        public int IdSede { get; set; }
        public int IdNivel { get; set; }
        public int IdJornada { get; set; }
        public int IdCurso { get; set; }
        public int IdDocumento { get; set; }
        public string NomDocumento { get; set; }
        public Nullable<int> OrdenDocumento { get; set; }
    
        public virtual aca_AnioLectivo_Jornada_Curso aca_AnioLectivo_Jornada_Curso { get; set; }
        public virtual aca_Documento aca_Documento { get; set; }
    }
}
