//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class aca_parametro
    {
        public int IdEmpresa { get; set; }
        public string RutaImagen_Alumno { get; set; }
        public string RutaImagen_Profesor { get; set; }
        public string RutaImagen_Seguimiento { get; set; }
    }
}
