//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_ArchivoRecaudacion
    {
        public int IdEmpresa { get; set; }
        public decimal IdArchivo { get; set; }
        public int IdBanco { get; set; }
        public int IdProceso_bancario { get; set; }
        public string Nom_Archivo { get; set; }
        public int SecuencialDescarga { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
        public string Observacion { get; set; }
        public double Valor { get; set; }
        public double ValorProntoPago { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public string IdUsuarioProceso { get; set; }
    
        public virtual ba_Banco_Cuenta ba_Banco_Cuenta { get; set; }
    }
}
