//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cp_proveedor()
        {
            this.cp_nota_DebCre = new HashSet<cp_nota_DebCre>();
            this.cp_orden_giro = new HashSet<cp_orden_giro>();
            this.cp_proveedor_codigo_SRI = new HashSet<cp_proveedor_codigo_SRI>();
            this.cp_proveedor_detalle = new HashSet<cp_proveedor_detalle>();
            this.cp_SolicitudPago = new HashSet<cp_SolicitudPago>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdProveedor { get; set; }
        public decimal IdPersona { get; set; }
        public string pr_codigo { get; set; }
        public string pr_contribuyenteEspecial { get; set; }
        public int pr_plazo { get; set; }
        public string pr_estado { get; set; }
        public string IdCiudad { get; set; }
        public string IdCtaCble_CXP { get; set; }
        public string IdCtaCble_Gasto { get; set; }
        public string IdCtaCble_Anticipo { get; set; }
        public int IdClaseProveedor { get; set; }
        public string MotivoAnulacion { get; set; }
        public string IdTipoCta_acreditacion_cat { get; set; }
        public string num_cta_acreditacion { get; set; }
        public Nullable<int> IdBanco_acreditacion { get; set; }
        public bool es_empresa_relacionada { get; set; }
        public string pr_telefonos { get; set; }
        public string pr_celular { get; set; }
        public string pr_direccion { get; set; }
        public string pr_correo { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
    
        public virtual cp_catalogo cp_catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cp_nota_DebCre> cp_nota_DebCre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cp_orden_giro> cp_orden_giro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cp_proveedor_codigo_SRI> cp_proveedor_codigo_SRI { get; set; }
        public virtual cp_proveedor_clase cp_proveedor_clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cp_proveedor_detalle> cp_proveedor_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cp_SolicitudPago> cp_SolicitudPago { get; set; }
    }
}
