//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_CobroMasivoDet
    {
        public int IdEmpresa { get; set; }
        public decimal IdCobroMasivo { get; set; }
        public int Secuencia { get; set; }
        public decimal IdAlumno { get; set; }
        public double Valor { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<decimal> IdCobro { get; set; }
    
        public virtual cxc_cobro cxc_cobro { get; set; }
        public virtual cxc_CobroMasivo cxc_CobroMasivo { get; set; }
    }
}
