//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_notaCreDeb_MasivaDet
    {
        public int IdEmpresa { get; set; }
        public decimal IdNCMasivo { get; set; }
        public int Secuencia { get; set; }
        public decimal IdAlumno { get; set; }
        public double Subtotal { get; set; }
        public double IVA { get; set; }
        public double vt_por_iva { get; set; }
        public string IdCod_Impuesto_Iva { get; set; }
        public double Total { get; set; }
        public string ObservacionDet { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<decimal> IdNota { get; set; }
    
        public virtual fa_notaCreDeb fa_notaCreDeb { get; set; }
    }
}
