//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesInventario : DbContext
    {
        public EntitiesInventario()
            : base("name=EntitiesInventario")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<in_Producto> in_Producto { get; set; }
        public virtual DbSet<in_categorias> in_categorias { get; set; }
        public virtual DbSet<in_presentacion> in_presentacion { get; set; }
        public virtual DbSet<in_ProductoTipo> in_ProductoTipo { get; set; }
        public virtual DbSet<in_Producto_x_fa_NivelDescuento> in_Producto_x_fa_NivelDescuento { get; set; }
        public virtual DbSet<in_parametro> in_parametro { get; set; }
        public virtual DbSet<in_grupo> in_grupo { get; set; }
        public virtual DbSet<in_linea> in_linea { get; set; }
        public virtual DbSet<in_Marca> in_Marca { get; set; }
        public virtual DbSet<in_subgrupo> in_subgrupo { get; set; }
    }
}
