//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesRRHH : DbContext
    {
        public EntitiesRRHH()
            : base("name=EntitiesRRHH")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ro_empleado> ro_empleado { get; set; }
        public virtual DbSet<vwro_empleado_combo> vwro_empleado_combo { get; set; }
        public virtual DbSet<vwro_empleado_datos_generales> vwro_empleado_datos_generales { get; set; }
        public virtual DbSet<vwro_empleados_consulta> vwro_empleados_consulta { get; set; }
    }
}
