//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesContabilidad : DbContext
    {
        public EntitiesContabilidad()
            : base("name=EntitiesContabilidad")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ct_cbtecble> ct_cbtecble { get; set; }
        public virtual DbSet<ct_cbtecble_det> ct_cbtecble_det { get; set; }
        public virtual DbSet<ct_periodo> ct_periodo { get; set; }
        public virtual DbSet<vwct_cbtecble_det> vwct_cbtecble_det { get; set; }
        public virtual DbSet<vwct_cbtecble> vwct_cbtecble { get; set; }
        public virtual DbSet<ct_cbtecble_Reversado> ct_cbtecble_Reversado { get; set; }
        public virtual DbSet<ct_cbtecble_tipo> ct_cbtecble_tipo { get; set; }
        public virtual DbSet<vwct_periodo> vwct_periodo { get; set; }
        public virtual DbSet<ct_CierrePorModuloPorSucursal> ct_CierrePorModuloPorSucursal { get; set; }
        public virtual DbSet<ct_parametro> ct_parametro { get; set; }
    }
}
