//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_rol_x_prestamo_detalle
    {
        public int IdEmpresa { get; set; }
        public decimal IdRol { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> IdEmpresa_pre { get; set; }
        public Nullable<decimal> IdPrestamo { get; set; }
        public Nullable<int> NumCuota { get; set; }
        public string Observacion { get; set; }
    
        public virtual ro_rol ro_rol { get; set; }
    }
}
