//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_AlumnoDocumento
    {
        public int IdEmpresa { get; set; }
        public decimal IdAlumno { get; set; }
        public int IdDocumento { get; set; }
        public string NomDocumento { get; set; }
        public bool EnArchivo { get; set; }
        public int OrdenDocumento { get; set; }
    }
}
