//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_Familia
    {
        public int IdEmpresa { get; set; }
        public decimal IdAlumno { get; set; }
        public int IdCatalogoPAREN { get; set; }
        public string NomCatalogo { get; set; }
        public decimal IdPersona { get; set; }
        public string pe_Naturaleza { get; set; }
        public string IdTipoDocumento { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string Direccion { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public bool SeFactura { get; set; }
        public string pe_sexo { get; set; }
        public string IdEstadoCivil { get; set; }
        public Nullable<System.DateTime> pe_fechaNacimiento { get; set; }
        public string CodCatalogoSangre { get; set; }
        public string CodCatalogoCONADIS { get; set; }
        public Nullable<double> PorcentajeDiscapacidad { get; set; }
        public string NumeroCarnetConadis { get; set; }
        public string pe_telfono_Contacto { get; set; }
        public int Secuencia { get; set; }
        public bool EsRepresentante { get; set; }
        public string pe_razonSocial { get; set; }
        public Nullable<int> IdProfesion { get; set; }
        public Nullable<int> IdCatalogoFichaInst { get; set; }
        public string EmpresaTrabajo { get; set; }
        public string DireccionTrabajo { get; set; }
        public string TelefonoTrabajo { get; set; }
        public string CargoTrabajo { get; set; }
        public Nullable<int> AniosServicio { get; set; }
        public Nullable<double> IngresoMensual { get; set; }
        public bool VehiculoPropio { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public bool CasaPropia { get; set; }
        public Nullable<int> AnioVehiculo { get; set; }
        public Nullable<int> IdReligion { get; set; }
        public Nullable<bool> AsisteCentroCristiano { get; set; }
        public bool EstaFallecido { get; set; }
        public Nullable<int> IdGrupoEtnico { get; set; }
        public string IdPais { get; set; }
        public string Cod_Region { get; set; }
        public string IdProvincia { get; set; }
        public string IdCiudad { get; set; }
        public string IdParroquia { get; set; }
        public string Sector { get; set; }
        public bool Estado { get; set; }
        public string Telefono { get; set; }
    }
}
