//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWACA_009
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public int Secuencia { get; set; }
        public decimal IdAlumno { get; set; }
        public string Codigo { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_cedulaRuc { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Observacion { get; set; }
        public int IdAnio { get; set; }
        public string Descripcion { get; set; }
        public string IdUsuarioCreacion { get; set; }
    }
}
