//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWACA_003
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public decimal IdAlumno { get; set; }
        public string NomRepresentante { get; set; }
        public string CedulaRepresentante { get; set; }
        public string NomSeFactura { get; set; }
        public string CedulaSeFactura { get; set; }
        public string NomAlumno { get; set; }
        public string CedulaAlumno { get; set; }
        public string NomCurso { get; set; }
        public string DescripcionActual { get; set; }
        public string DescripcionAnterior { get; set; }
        public string Direccion { get; set; }
        public string DescripcionPensiones { get; set; }
        public string CorreoSeFactura { get; set; }
        public string CorreoRepresentante { get; set; }
        public string DireccionRepresentante { get; set; }
        public string NacionalidadRepresentante { get; set; }
        public string SectorRepresentante { get; set; }
        public string CelularRepresentante { get; set; }
    }
}
