//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWACA_001_Familiares
    {
        public int IdEmpresa { get; set; }
        public decimal IdAlumno { get; set; }
        public int Secuencia { get; set; }
        public int IdCatalogoPAREN { get; set; }
        public string NomInstruccion { get; set; }
        public string NomCatalogo { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string NomEstadoCivil { get; set; }
        public string Direccion { get; set; }
        public string EmpresaTrabajo { get; set; }
        public string NomProfesion { get; set; }
        public string Correo { get; set; }
        public string Celular { get; set; }
        public Nullable<double> SueldoPadre { get; set; }
        public Nullable<double> Sueldo { get; set; }
        public Nullable<double> OtrosIngresos { get; set; }
        public string VehiculoPropio { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> AniosServicio { get; set; }
        public Nullable<int> AnioVehiculo { get; set; }
        public string Titulo { get; set; }
    }
}
