//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_AnioLectivo_Curso_Plantilla_Parametrizacion
    {
        public int IdEmpresa { get; set; }
        public int IdAnio { get; set; }
        public int IdSede { get; set; }
        public int IdNivel { get; set; }
        public int IdJornada { get; set; }
        public int IdCurso { get; set; }
        public int IdPlantilla { get; set; }
        public int IdRubro { get; set; }
        public string NomJornada { get; set; }
        public Nullable<int> OrdenJornada { get; set; }
        public string NomCurso { get; set; }
        public Nullable<int> OrdenCurso { get; set; }
        public string NomPlantilla { get; set; }
        public string NomRubro { get; set; }
        public string NomNivel { get; set; }
        public string NomSede { get; set; }
        public string IdCtaCbleDebe { get; set; }
        public string IdCtaCbleHaber { get; set; }
        public string pc_CuentaDebe { get; set; }
        public string pc_CuentaHaber { get; set; }
    }
}
