//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_Matricula_Rubro_FacturaMasiva
    {
        public int IdEmpresa { get; set; }
        public int IdAnio { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<decimal> IdCbteVta { get; set; }
        public decimal IdAlumno { get; set; }
        public string pe_nombreCompleto { get; set; }
        public decimal Total { get; set; }
        public string Correo { get; set; }
        public string vt_autorizacion { get; set; }
    }
}
