//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_Alumno_PeriodoActual
    {
        public int IdEmpresa { get; set; }
        public string Codigo { get; set; }
        public decimal IdAlumno { get; set; }
        public decimal IdMatricula { get; set; }
        public string NombreAlumno { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string NombreRepresentante { get; set; }
        public string CorreoRepresentante { get; set; }
        public string NombreEmiteFactura { get; set; }
        public string CorreoEmiteFactura { get; set; }
        public string CelularRepresentante { get; set; }
        public string CelularEmiteFactura { get; set; }
        public string TelefonoRepresentante { get; set; }
        public string TelefonoEmiteFactura { get; set; }
        public int IdAnio { get; set; }
        public int IdSede { get; set; }
        public int IdNivel { get; set; }
        public int IdJornada { get; set; }
        public int IdCurso { get; set; }
        public int IdParalelo { get; set; }
        public string NomSede { get; set; }
        public string NomNivel { get; set; }
        public string NomJornada { get; set; }
        public string NomCurso { get; set; }
        public string NomParalelo { get; set; }
        public double Saldo { get; set; }
        public double SaldoProntoPago { get; set; }
        public int CantDeudas { get; set; }
        public string NomPlantillaTipo { get; set; }
    }
}
