//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_Menu_x_seg_usuario
    {
        public int IdEmpresa { get; set; }
        public int IdSede { get; set; }
        public int IdMenu { get; set; }
        public string DescripcionMenu { get; set; }
        public string web_nom_Area { get; set; }
        public string web_nom_Controller { get; set; }
        public string web_nom_Action { get; set; }
        public string IdUsuario { get; set; }
        public bool Nuevo { get; set; }
        public bool Modificar { get; set; }
        public bool Anular { get; set; }
    }
}
