//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_Hermanos
    {
        public int IdEmpresa { get; set; }
        public decimal IdAlumno { get; set; }
        public Nullable<int> IdAnio { get; set; }
        public Nullable<int> IdCurso { get; set; }
        public string Descripcion { get; set; }
        public int IdCatalogoPAREN { get; set; }
        public decimal IdPersona { get; set; }
        public string NomCurso { get; set; }
        public string NomParalelo { get; set; }
        public string pe_nombreCompleto { get; set; }
    }
}
