//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_Matricula_Rubro_PorFacturar
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public int IdPeriodo { get; set; }
        public int IdRubro { get; set; }
        public decimal IdMecanismo { get; set; }
        public decimal IdProducto { get; set; }
        public bool EnMatricula { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public string IdCod_Impuesto_Iva { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public Nullable<double> ValorIVA { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<decimal> IdCbteVta { get; set; }
        public Nullable<System.DateTime> FechaFacturacion { get; set; }
        public int IdAnio { get; set; }
        public int IdSede { get; set; }
        public decimal IdAlumno { get; set; }
        public bool AplicaProntoPago { get; set; }
        public string NomRubro { get; set; }
        public string pr_descripcion { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public string DescripcionCuotas { get; set; }
        public Nullable<double> ValorProntoPago { get; set; }
        public Nullable<System.DateTime> FechaProntoPago { get; set; }
        public string Periodo { get; set; }
        public int IdPlantilla { get; set; }
    }
}
