//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_AnioLectivo_Paralelo_Profesor
    {
        public int IdEmpresa { get; set; }
        public int IdAnio { get; set; }
        public int IdSede { get; set; }
        public int IdNivel { get; set; }
        public int IdJornada { get; set; }
        public int IdCurso { get; set; }
        public int IdMateria { get; set; }
        public int IdParalelo { get; set; }
        public Nullable<decimal> IdProfesor { get; set; }
        public Nullable<decimal> IdPersona { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string NomMateria { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<int> IdCatalogoTipoCalificacion { get; set; }
    }
}
