//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_AlumnoRetiro
    {
        public int IdEmpresa { get; set; }
        public decimal IdRetiro { get; set; }
        public decimal IdAlumno { get; set; }
        public decimal IdPersona { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_nombreCompleto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public int IdCatalogoESTALU { get; set; }
        public string IdUsuarioAnulacion { get; set; }
    }
}
