//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_Tematica
    {
        public int IdEmpresa { get; set; }
        public int IdTematica { get; set; }
        public int IdCampoAccion { get; set; }
        public string NombreTematica { get; set; }
        public int OrdenTematica { get; set; }
        public bool Estado { get; set; }
        public string NombreCampoAccion { get; set; }
        public int OrdenCampoAccion { get; set; }
    }
}
