//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_MecanismoDePago
    {
        public int IdEmpresa { get; set; }
        public decimal IdMecanismo { get; set; }
        public string NombreMecanismo { get; set; }
        public string IdTerminoPago { get; set; }
        public string nom_TerminoPago { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string No_Descripcion { get; set; }
    }
}
