//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwaca_MatriculaAsistencia
    {
        public int IdEmpresa { get; set; }
        public decimal IdMatricula { get; set; }
        public int IdAnio { get; set; }
        public int IdSede { get; set; }
        public int IdNivel { get; set; }
        public int IdJornada { get; set; }
        public int IdCurso { get; set; }
        public int IdParalelo { get; set; }
        public decimal IdAlumno { get; set; }
        public string Codigo { get; set; }
        public string pe_nombreCompleto { get; set; }
        public Nullable<int> FInjustificadaP1 { get; set; }
        public Nullable<int> FJustificadaP1 { get; set; }
        public Nullable<int> AtrasosP1 { get; set; }
        public Nullable<int> FInjustificadaP2 { get; set; }
        public Nullable<int> FJustificadaP2 { get; set; }
        public Nullable<int> AtrasosP2 { get; set; }
        public Nullable<int> FInjustificadaP3 { get; set; }
        public Nullable<int> FJustificadaP3 { get; set; }
        public Nullable<int> AtrasosP3 { get; set; }
        public Nullable<int> FInjustificadaP4 { get; set; }
        public Nullable<int> FJustificadaP4 { get; set; }
        public Nullable<int> AtrasosP4 { get; set; }
        public Nullable<int> FInjustificadaP5 { get; set; }
        public Nullable<int> FJustificadaP5 { get; set; }
        public Nullable<int> AtrasosP5 { get; set; }
        public Nullable<int> FInjustificadaP6 { get; set; }
        public Nullable<int> FJustificadaP6 { get; set; }
        public Nullable<int> AtrasosP6 { get; set; }
        public Nullable<decimal> IdProfesorTutor { get; set; }
        public Nullable<decimal> IdProfesorInspector { get; set; }
    }
}
