//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_ArchivoRecaudacionDet_Saldos
    {
        public int IdEmpresa { get; set; }
        public Nullable<decimal> IdAlumno { get; set; }
        public decimal IdMatricula { get; set; }
        public string CodigoAlumno { get; set; }
        public string pe_nombreCompleto { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> SaldoProntoPago { get; set; }
        public Nullable<System.DateTime> FechaProntoPago { get; set; }
    }
}
