//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_cartera_cobrada_saldo0
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public string vt_tipoDoc { get; set; }
        public string vt_NunDocumento { get; set; }
        public string vt_Observacion { get; set; }
        public decimal IdCbteVta { get; set; }
        public string CodCbteVta { get; set; }
        public string Su_Descripcion { get; set; }
        public decimal IdCliente { get; set; }
        public Nullable<decimal> IdAlumno { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public decimal Total { get; set; }
        public System.DateTime vt_fech_venc { get; set; }
        public string pe_nombreCompleto { get; set; }
        public Nullable<int> IdAnio { get; set; }
        public Nullable<int> IdPlantilla { get; set; }
        public Nullable<int> IdPuntoVta { get; set; }
        public double dc_ValorPago { get; set; }
    }
}
