//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFAC_009
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdNota { get; set; }
        public int IdSucursal_fac_nd_doc_mod { get; set; }
        public int IdBodega_fac_nd_doc_mod { get; set; }
        public decimal IdCbteVta_fac_nd_doc_mod { get; set; }
        public string vt_tipoDoc { get; set; }
        public System.DateTime no_fecha { get; set; }
        public string sc_observacion { get; set; }
        public string vt_Observacion { get; set; }
        public int IdTipoNota { get; set; }
        public string No_Descripcion { get; set; }
        public System.DateTime fecha_cruce { get; set; }
        public decimal Total { get; set; }
        public double Valor_Aplicado { get; set; }
        public string Tipo { get; set; }
        public string vt_NumFactura { get; set; }
        public Nullable<decimal> IdAlumno { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string CodigoAlumno { get; set; }
        public Nullable<System.DateTime> vt_fecha { get; set; }
        public Nullable<decimal> IdConciliacion { get; set; }
    }
}
